CREATE DATABASE Dw_Finance_Accounts;

CREATE MULTISET TABLE DIM_PERSON (
    person_sk   INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    person_id   CHAR(1) NOT NULL,
    person_name VARCHAR(100) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    is_current  BYTEINT DEFAULT 1
)
UNIQUE PRIMARY INDEX (person_sk)
PARTITION BY RANGE_N(start_date BETWEEN DATE '2020-01-01'
AND DATE '2030-12-31' EACH INTERVAL '1' MONTH);

CREATE MULTISET TABLE DIM_ACCOUNT (
    account_sk  INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    acc_no      INTEGER NOT NULL,
    acc_status  VARCHAR(20) NOT NULL,
    acc_type    VARCHAR(10) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    is_current  BYTEINT DEFAULT 1
)
UNIQUE PRIMARY INDEX (account_sk)
PARTITION BY RANGE_N(start_date BETWEEN DATE '2020-01-01'
AND DATE '2030-12-31' EACH INTERVAL '1' MONTH);

CREATE INDEX (acc_no) ON DIM_ACCOUNT;

CREATE MULTISET TABLE DIM_DATE (
    date_sk     INTEGER NOT NULL,
    full_date   DATE NOT NULL,
    day_num     BYTEINT,
    month_num   BYTEINT,
    month_name  VARCHAR(10),
    quarter_num BYTEINT,
    year_num    SMALLINT
)
UNIQUE PRIMARY INDEX (date_sk);

CREATE MULTISET TABLE DIM_PERSON_IDEN (
    iden_sk     INTEGER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    person_sk   INTEGER NOT NULL,
    id_value    VARCHAR(50) NOT NULL,
    id_type     VARCHAR(20) NOT NULL,
    start_date  DATE NOT NULL
)
UNIQUE PRIMARY INDEX (iden_sk)
PARTITION BY RANGE_N(start_date BETWEEN DATE '2020-01-01'
AND DATE '2030-12-31' EACH INTERVAL '1' MONTH);

CREATE MULTISET TABLE BRIDGE_PERSON_ACCOUNT (
    person_sk   INTEGER NOT NULL,
    account_sk  INTEGER NOT NULL
)
PRIMARY INDEX (person_sk, account_sk);

CREATE MULTISET TABLE FACT_ACCOUNT_SNAPSHOT (
    date_sk     INTEGER NOT NULL,
    person_sk   INTEGER NOT NULL,
    account_sk  INTEGER NOT NULL,
    status_flag BYTEINT NOT NULL
)
PRIMARY INDEX (account_sk, date_sk)
PARTITION BY RANGE_N(date_sk BETWEEN 20200101 AND 20301231 EACH 1);
